USE [master]
GO

/****** Object:  Database [PRODEV]    Script Date: 2014-11-26 1:22:53 PM ******/
CREATE DATABASE [PRODEV]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PRODEV', FILENAME = N'D:\SQL\2012\Data\PRODEV.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PRODEV_log', FILENAME = N'D:\SQL\2012\Log\PRODEV_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PRODEV] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PRODEV].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PRODEV] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PRODEV] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PRODEV] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PRODEV] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PRODEV] SET ARITHABORT OFF 
GO

ALTER DATABASE [PRODEV] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PRODEV] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [PRODEV] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PRODEV] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PRODEV] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PRODEV] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PRODEV] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PRODEV] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PRODEV] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PRODEV] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PRODEV] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PRODEV] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PRODEV] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PRODEV] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PRODEV] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PRODEV] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PRODEV] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PRODEV] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PRODEV] SET RECOVERY FULL 
GO

ALTER DATABASE [PRODEV] SET  MULTI_USER 
GO

ALTER DATABASE [PRODEV] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PRODEV] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PRODEV] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PRODEV] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PRODEV] SET  READ_WRITE 
GO

