USE [PRODEV]
GO

/****** Object:  Table [dbo].[COREENTITY]    Script Date: 2014-11-27 4:15:14 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COREENTITY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nchar](32) NOT NULL,
	[GEOPOLY] [geography] NOT NULL,
	[DATEBEGIN] [datetime] NULL,
	[DATEEND] [datetime] NULL,
 CONSTRAINT [PK_COREENTITY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

