USE [PRODEV]
GO

/****** Object:  Table [dbo].[COREENTITY]    Script Date: 2015-02-02 11:55:43 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COREENTITY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](32) NOT NULL,
	[POLY_GEOMETRY] [geometry] NOT NULL,
	[POLY_GEOGRAPHY] [geography] NULL,
	[DATEBEGIN] [datetime] NULL,
	[DATEEND] [datetime] NULL,
 CONSTRAINT [PK_COREENTITY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
